### ISSUE TITLE
[feature_request] personal glycemic state (PGS) metric

### ISSUE THREAD

**Issue by seb-sauer** [irinagain/iglu#116]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5467104/

This is a relatively new metric, that is very useful. Hence, it is increasingly popular. Dexcom, xdrip+ , nightscout et al already support it.
Unfortunately, iglu currently lacks support .

**Comment by irinagain** [comment]
Thank you for bringing this to our attention. I am currently on maternity leave so will not be able to look at it until Fall, but hopefully can start working on incorporating it then.

**Comment by irinagain** [comment]
I appreciate your patience. We just made an update that implements PGS metric. It's on CRAN yet, but if you download the latest github version, it's function `pgs`
