### ISSUE TITLE
Unable to calculate MAGE

### ISSUE THREAD

**Issue by dhairya02** [irinagain/iglu#147]
Hi, 
My current dataframe is for single participant and I am getting the following error. Not sure what could be the issue
```
> mage(glucose_data,
+      version = c("ma"),
+      sd_multiplier = 1,
+      short_ma = 5,
+      long_ma = 32,
+      return_type = "num",
+      dt0 = 15,
+      direction = "avg",
+      inter_gap = 45,
+      max_gap = 180,
+      plot = FALSE,
+      title = NA,
+      xlab = NA,
+      ylab = NA,
+      show_ma = FALSE,
+      show_excursions = TRUE
+ )
Error in `[.default`(tr, timeindex - 1) : 
  only 0's may be mixed with negative subscripts
> colnames(glucose_data)
[1] "time" "gl"   "id"  
```

**Comment by Nathaniel-Fernandes** [comment]
Hi! Thank you for your comment.

Would it be possible to upload an example csv of the `glucose_data` you are using?

Without an example I can only speculate, but 2 possible explanations jump to mind:
1. Are you using a grouped data frame? You might need to call `ungroup` first: [see here](https://stackoverflow.com/a/64493522/21711054).
2. What data type are your `id`s (i.e., numbers or strings)? If they're numbers, try to convert them to strings and see if you still get the same error message.

**Comment by dhairya02** [comment]
I was able to solve this by adding a line that converted the timestamp column from AM/PM to 24 hour format. That seems to solve the issue.

`if (!inherits(glucose_data$time, c("POSIXct", "POSIXlt"))) {
    glucose_data$time <- tryCatch({
      mdy_hm(glucose_data$time)
    }, error = function(e) {
      message("Failed to parse datetime, check format: ", e$message)
      NA
    })
  }`
  
  Maybe having something similar in the function could solve this for future users.

**Comment by Nathaniel-Fernandes** [comment]
Thank you for your comment, and I'm glad you were able to solve the issue!
