### ISSUE TITLE
Interpolate function fails on BGM data.

### ISSUE THREAD

**Issue by dbuckpersonal** [irinagain/iglu#3]
where data is the clean data and subj is created as follows:
subj = data[data$id == data$id[1,] #Get only the first subject
subj$time = as.POSIXct(subj$time) #Force time format
call:
iglu:::CGMS2DayByDay(subj)
Error message:
Error in rep(dt0, ndays * 24 * 60/dt0) : invalid 'times' argument

**Comment by irinagain** [comment]
In the code below from CGMS2DayByDay run on the data, what are the values of dt0 and ndays on BGM? The idea is that ndays should be the number of days of measurements; and dt0 should be difference in minutes between two consecutive measurements.

 data = read_df_or_vec(data[complete.cases(data),])

  ### Get glycemic data
  g = data$gl
  t = data$time
  t = t[!is.na(g)]
  tr = as.POSIXct(t)

  timeindex = 2:length(tr)
  timediff = difftime(tr[timeindex], tr[timeindex - 1], units = "mins")
  dt0 = as.double(round(median(timediff, na.rm = T)))
 ndays = ceiling(as.double(difftime(max(tr), min(tr), units = "days")) + 1)

**Comment by irinagain** [comment]
Sorting issue in the original data, package will now warn and auto-sort times
