### ISSUE TITLE
hypoglycemic is wrong

### ISSUE THREAD

**Issue by muschellij2** [irinagain/iglu#4]
Are you sure this is the equation
\sum(glucose) * n /30? 
 https://github.com/stevebroll/iglu/blob/master/R/hypo_index.R#L19 

The real issue is that single raises to 2 power:
https://github.com/stevebroll/iglu/blob/master/R/hypo_index.R#L50
but multi is 1.1:
https://github.com/stevebroll/iglu/blob/master/R/hypo_index.R#L60

**Comment by irinagain** [comment]
The documentation and code have been corrected to be consistent
