### ISSUE TITLE
Differnece in claculcation

### ISSUE THREAD

**Issue by muschellij2** [irinagain/iglu#5]
In https://github.com/stevebroll/iglu/blob/master/R/hbgi.R#L22, the power is grouped together (aka it's all to the power of the difference), but in 
https://github.com/stevebroll/iglu/blob/master/R/hbgi.R#L49 it's not that calculation

**Comment by muschellij2** [comment]
Also, from Interpretation of Continuous Glucose Monitoring Data: Glycemic Variability and Quality of Glycemic Control, HBGI is (LBGI is < 112.5)
For glucose values >=112.5 mg=dL,
22.77 * 1/n  * \sum ( (log(gl)^{1.084} - 5.381)^2

so I'm unsure how this calc is happening

**Comment by irinagain** [comment]
This is a typo in the original paper that we caught. Here is [the letter to the editor that explains it ](https://www.liebertpub.com/doi/abs/10.1089/dia.2018.0057?journalCode=dia). I think we need to add that citation in the documentation, although the original paper I believe may not have that typo.
